# Generated by Django 3.1.6 on 2021-04-10 17:24

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.FileField(blank=True, upload_to='')),
                ('content_type', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=500)),
                ('product_value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('starting_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('min_bid_increment', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('bid_count', models.IntegerField(default=0)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('bio_text', models.CharField(max_length=500)),
                ('profile_picture', models.FileField(blank=True, upload_to='')),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('update_time', models.DateTimeField(default=datetime.datetime(2021, 4, 10, 13, 24, 39, 835384))),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('price', models.FloatField()),
                ('auction_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybid.auctionitem')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
