# Generated by Django 3.1.7 on 2021-04-15 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybid', '0003_auto_20210415_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 1, 8, 37, 634603)),
        ),
    ]
