# Generated by Django 3.1.7 on 2021-04-15 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybid', '0004_auto_20210415_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 1, 12, 36, 450452)),
        ),
    ]
