# Generated by Django 3.1.7 on 2021-04-16 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybid', '0005_auto_20210415_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 2, 12, 31, 518387)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 2, 12, 31, 517995)),
        ),
    ]
