# Generated by Django 3.1.7 on 2021-04-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybid', '0006_auto_20210416_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='update_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='update_time',
            field=models.DateTimeField(),
        ),
    ]
