# Generated by Django 3.1.7 on 2021-04-18 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybid', '0010_auto_20210418_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 5, 39, 21, 581016)),
        ),
    ]
