# Generated by Django 3.1.7 on 2021-04-23 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybid', '0012_auto_20210418_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 23, 30, 19, 765577)),
        ),
    ]
