# Generated by Django 3.1.7 on 2021-04-30 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybid', '0014_auto_20210424_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 30, 2, 54, 3, 381329)),
        ),
    ]
