# Generated by Django 3.1.7 on 2021-04-30 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybid', '0018_auto_20210430_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 30, 4, 38, 56, 706927)),
        ),
    ]
